name: Validations

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
jobs:  
  cache_memory_usage:
    name: Cache Memory Usage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
  
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
  
      - name: Set up Android SDK
        uses: actions/setup-android@v3
        with:
          sdk-version: '30'
  
      - name: Create emulator
        run: |
          echo no | avdmanager create avd --force --name test --abi goggle_apis/x86_64 --package 
          'system-images;android-30;google_apis;x86_64'
  
      - name: Start emulator
        run: |
          $ANDROID_HOME/emulator/emulator-avd test -no-skin -no-audio -no-window &
  
      - name: Wait for emulator to start
        run: |
          ./android-wait-for-emulator.sh sleep 30
          adb shell input keyevent 82
  
      - name: Print processes
        run: adb shell top
